#!/usr/bin/python3 -u

print("Location:https://www.google.com/search?q=pikachu\n", end="")
print("Status: 302 Found\n", end="")
print("Content-Type: text/html\n", end="")
print("ExtensionField: hoge\n", end="")
print("ProtocolField: fuga\n", end="")
print("\n", end="")
print("<HTML>\n", end="")
print("<body><p>Let's redirect!!</p></body>\n", end="")
print("</HTML>", end="")
