#!/usr/bin/python3 -u

print("Content-Type: text/html\n", end="")
print("Optional: hoge\n", end="")
print("\n", end="")
print("<HTML>\n", end="")
print("<body><p>200 OK</p></body>\n", end="")
print("</HTML>", end="")
