#!/usr/bin/python3 -u

import sys

print("Content-type: text/plain; charset=iso-8859-1")
print()

print("TOUPPER")

s = sys.stdin.read()

print()
print("input len ", len(s))
print("--- --- ----")
print(s.upper())
print("--- --- ----")
print("TOUPPER END")
