#!/usr/bin/python3 -u

import sys
import datetime
import time

start_time = datetime.datetime.now()

print("Content-Type: text/plain")
print()
for _ in range(20):
    print(f"{datetime.datetime.now() - start_time}[sec]")
    time.sleep(0.5)

# CGIが出力しなくなってからどのくらいの時間プロセスが生きているか見るためのprint
while True:
    print(f"{datetime.datetime.now() - start_time}[sec]", file=sys.stderr)
    time.sleep(0.5)
