name: REQ-TEST

# プルリクエスト or 手動実行
on: [pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # テストを実行
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout git repository
        uses: actions/checkout@v2

      - name: req-test
        run: bash -c "timeout 300 make req-test WEBSERV_PORT=8080 RUN_CMP_TEST=0"
